### ISSUE TITLE
Applying to become part of the Ethereum Classic TweetTogether approval team

### ISSUE THREAD

**Issue by Soteria-Smart-Contracts** [ethereumclassic/twitter-together#24]
Please let us know if there is anything specific needed in order to join this team. 
Thank you.

**Comment by IstoraMandiri** [comment]
Yes, we'll need to consider what requirements are.

Currently we have about 10 people with permissions to approve, which is probably enough, but they aren't all active, and there's benefit in having people in different timezones to ensure there's 24/hr coverage.

We should probably also have a dedicated management team rather than the web-developmet team, as they are different responsibilities.

Pinging @realcodywburns - no action required now, but something to have on your radar once we have figured this out.

**Comment by w1g0** [comment]
We can set this on the agenda for the coming Community Call.

**Comment by w1g0** [comment]
When I would like to transfer it to another repo it only gives the website as an option, can we have it sent to the Community Call repo?

**Comment by Soteria-Smart-Contracts** [comment]
Any news @w1g0?

**Comment by w1g0** [comment]
As mentioned before, it will have to be discussed on the next community call, we don't decide.

**Comment by IstoraMandiri** [comment]
Hi @Soteria-Smart-Contracts , we're open to recruiting new maintainers so please make a post in #71 

Thank you.
