### ISSUE TITLE
In the readme.md file we can replace @eth_classic with @ETC_Network and the way to reply can be deleted imho

### ISSUE THREAD

**Issue by w1g0** [ethereumclassic/twitter-together#42]

**Comment by IstoraMandiri** [comment]
Please could you be a bit more precise with these kinds of issues?

I cannot find a reference to @eth_classic in the `./readme.md` file.

I don't understand what you mean by "the way to reply can be deleted" imho.

**Comment by w1g0** [comment]
https://github.com/ethereumclassic/twitter-together/tree/main/tweets
![2022-09-14_13h30_17](https://user-images.githubusercontent.com/67763069/190142629-b3a0e8c9-c25a-4061-b3b7-8433e47da5e4.png)

**Comment by IstoraMandiri** [comment]
Ah, gotcha. Until #27 is fixed, now that this is becoming a more serious project it'd be great if we could create granular issues with a rough format  like such.

**Issue Title:** Update Tweets Readme Examples
**Issue Comment:** In https://github.com/ethereumclassic/twitter-together/blob/main/tweets/README.md, we are referencing the old twitter handle, instead we should reference the following tweet [reference tweet goes here] 

**Issue Title:** Remove Replies from Samples and Readme 
**Issue Comment:** Example of replies should be removed because ....

**Comment by Chief-Prince-Of-Function** [comment]
Here to help where I can. 
Attached is an image of the lines within the tweets/readme file. Also shows the reply section. 

![102A2D88-0363-46CD-A5BC-890020FBAD6E](https://user-images.githubusercontent.com/79958366/190147012-1c340f5e-68bf-4a0e-9c85-7566f520ddf5.jpeg)

**Comment by w1g0** [comment]
Thanks for the clarification @Chief-Prince-Of-Function
